import { Purchase } from "../types/purchase";

export const mockPurchases: Purchase[] = [
    {
      date: new Date(2024, 0, 15),
      voucher_number: "VOUCHER-5674",
      supplier: "Supplier E",
      purchased_product: {
        productId: "P-8745",
        productName: "Product 5",
        qty: 7,
        unitPrice: 21.99,
      },
      totalPrice: 153.93,
    },
    {
      date: new Date(2024, 1, 10),
      voucher_number: "VOUCHER-4352",
      supplier: "Supplier C",
      purchased_product: {
        productId: "P-2346",
        productName: "Product 2",
        qty: 4,
        unitPrice: 15.5,
      },
      totalPrice: 62.0,
    },
    {
      date: new Date(2024, 3, 20),
      voucher_number: "VOUCHER-1298",
      supplier: "Supplier F",
      purchased_product: {
        productId: "P-6789",
        productName: "Product 7",
        qty: 10,
        unitPrice: 9.99,
      },
      totalPrice: 99.9,
    },
    {
      date: new Date(2024, 5, 5),
      voucher_number: "VOUCHER-8923",
      supplier: "Supplier D",
      purchased_product: {
        productId: "P-3452",
        productName: "Product 3",
        qty: 8,
        unitPrice: 18.25,
      },
      totalPrice: 146.0,
    },
    {
      date: new Date(2024, 6, 18),
      voucher_number: "VOUCHER-7845",
      supplier: "Supplier A",
      purchased_product: {
        productId: "P-8903",
        productName: "Product 9",
        qty: 3,
        unitPrice: 12.99,
      },
      totalPrice: 38.97,
    },
    {
      date: new Date(2024, 7, 12),
      voucher_number: "VOUCHER-7834",
      supplier: "Supplier B",
      purchased_product: {
        productId: "P-1234",
        productName: "Product 1",
        qty: 5,
        unitPrice: 10.0,
      },
      totalPrice: 50.0,
    },
    {
      date: new Date(2024, 8, 9),
      voucher_number: "VOUCHER-6512",
      supplier: "Supplier G",
      purchased_product: {
        productId: "P-4590",
        productName: "Product 4",
        qty: 12,
        unitPrice: 13.5,
      },
      totalPrice: 162.0,
    },
    {
      date: new Date(2024, 9, 25),
      voucher_number: "VOUCHER-2567",
      supplier: "Supplier H",
      purchased_product: {
        productId: "P-3456",
        productName: "Product 6",
        qty: 6,
        unitPrice: 19.75,
      },
      totalPrice: 118.5,
    },
    {
      date: new Date(2024, 10, 3),
      voucher_number: "VOUCHER-1112",
      supplier: "Supplier I",
      purchased_product: {
        productId: "P-5678",
        productName: "Product 8",
        qty: 9,
        unitPrice: 8.99,
      },
      totalPrice: 80.91,
    },
    {
      date: new Date(2024, 11, 19),
      voucher_number: "VOUCHER-7753",
      supplier: "Supplier J",
      purchased_product: {
        productId: "P-9012",
        productName: "Product 10",
        qty: 4,
        unitPrice: 22.5,
      },
      totalPrice: 90.0,
    },
    {
      date: new Date(2024, 0, 7),
      voucher_number: "VOUCHER-1123",
      supplier: "Supplier E",
      purchased_product: {
        productId: "P-5671",
        productName: "Product 11",
        qty: 6,
        unitPrice: 30.0,
      },
      totalPrice: 180.0,
    },
    {
      date: new Date(2024, 1, 22),
      voucher_number: "VOUCHER-4231",
      supplier: "Supplier F",
      purchased_product: {
        productId: "P-3412",
        productName: "Product 12",
        qty: 8,
        unitPrice: 20.0,
      },
      totalPrice: 160.0,
    },
    {
      date: new Date(2024, 2, 17),
      voucher_number: "VOUCHER-3214",
      supplier: "Supplier B",
      purchased_product: {
        productId: "P-4599",
        productName: "Product 13",
        qty: 3,
        unitPrice: 40.0,
      },
      totalPrice: 120.0,
    },
    {
      date: new Date(2024, 3, 9),
      voucher_number: "VOUCHER-1129",
      supplier: "Supplier H",
      purchased_product: {
        productId: "P-5677",
        productName: "Product 14",
        qty: 2,
        unitPrice: 50.0,
      },
      totalPrice: 100.0,
    },
    {
      date: new Date(2024, 4, 14),
      voucher_number: "VOUCHER-9992",
      supplier: "Supplier J",
      purchased_product: {
        productId: "P-8910",
        productName: "Product 15",
        qty: 5,
        unitPrice: 25.0,
      },
      totalPrice: 125.0,
    },
    {
      date: new Date(2024, 5, 26),
      voucher_number: "VOUCHER-7712",
      supplier: "Supplier G",
      purchased_product: {
        productId: "P-1235",
        productName: "Product 16",
        qty: 10,
        unitPrice: 11.0,
      },
      totalPrice: 110.0,
    },
    {
      date: new Date(2024, 6, 8),
      voucher_number: "VOUCHER-5555",
      supplier: "Supplier A",
      purchased_product: {
        productId: "P-4352",
        productName: "Product 17",
        qty: 8,
        unitPrice: 14.5,
      },
      totalPrice: 116.0,
    },
    {
      date: new Date(2024, 7, 3),
      voucher_number: "VOUCHER-4142",
      supplier: "Supplier D",
      purchased_product: {
        productId: "P-6785",
        productName: "Product 18",
        qty: 12,
        unitPrice: 9.0,
      },
      totalPrice: 108.0,
    },
    {
      date: new Date(2024, 8, 15),
      voucher_number: "VOUCHER-8888",
      supplier: "Supplier C",
      purchased_product: {
        productId: "P-9014",
        productName: "Product 19",
        qty: 7,
        unitPrice: 23.5,
      },
      totalPrice: 164.5,
    },
    {
      date: new Date(2024, 9, 20),
      voucher_number: "VOUCHER-2022",
      supplier: "Supplier I",
      purchased_product: {
        productId: "P-3419",
        productName: "Product 20",
        qty: 4,
        unitPrice: 28.0,
      },
      totalPrice: 112.0,
    },
  ];
  